algoritmo "semnome"
// Função :
// Autor :
// Data : 21/03/2022
// Seção de Declarações 
var
base:real
altura:real
area:real

inicio
// Seção de Comandos

escreval("Digite o valor da base do triângulo: ")
leia(base)
escreval()
escreval("Digite o valor da altura do triângulo: ")
leia(altura)

area <- (base*altura/2)

escreval()
escreval("A área do triângulo é: ",area)


 
fimalgoritmo
