algoritmo "Exercicio_02"
// Função : Pedir para o usuário digitar um valor e informar se ele é par ou ímpar
// Autor : Arthur Siwerski Stachowski - 1F
// Data : 01/08/2022
// Seção de Declarações
 
var
numero: inteiro


inicio

escreval("Digite um número: ")
leia(numero)

se ((numero mod 2) = 0) entao
   escreval()
   escreval(numero," é par.")
senao
   escreval()
   escreval(numero," é ímpar.")
fimse

escreval()
escreval("Fim do programa")

 
fimalgoritmo
