algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
valor: real
qtde: real
vt: real
inicio
// Seção de Comandos
escreval("Digite o valor da peça: ")
leia(valor)
escreval("Digite a quantidade de peças: ")
leia(qtde)

// Processamento
vt <- qtde * valor

// Dados de Saída
escreval()
escreval()
escreval("O valor total é: ",vt)


fimalgoritmo
