algoritmo "Exemplo_03"
// Função :
// Autor :
// Data : 01/08/2022
// Seção de Declarações 
var
idade: inteiro

inicio
// Seção de Comandos

escreval("Digite a sua idade: ")
leia(idade)


se ((idade >= 18) e (idade < 50)) entao
   escreval("Você já tem idade para dirigir!")
senao
   escreval("Você está fora do intervalo permitido!")
fimse


escreval()
escreval()
escreval("Acabou o programa.")


fimalgoritmo
